/**
 * LinguisticPersonaService — Human-Like Communication & Adaptive Style System.
 *
 * Responsibilities:
 * - Maintains a compact, high-quality persona prompt that guides the AI to sound like
 *   a real human developer / teammate rather than a robotic assistant.
 * - Dynamically adapts to user slang, greetings (e.g. "вассап", "ку", "йоу"), tone,
 *   and brevity preferences without looking forced or cringe.
 * - Extracts linguistic speech patterns from past sessions with hash-based caching
 *   to avoid redundant re-analysis or wasted tokens.
 * - Fully customizable from UI (tone presets, custom instructions, auto-profile).
 * - Safe fallbacks: never crashes or blocks chat if offline or LLM fails.
 */

import fs from 'fs'
import path from 'path'
import { app } from 'electron'
import { ChatService, ChatConfig } from './ChatService'
import { SessionSummaryService } from './SessionSummaryService'

export type PersonaTone = 'adaptive' | 'casual' | 'direct' | 'friendly' | 'mentor'

export interface LinguisticPersona {
  tone: PersonaTone
  customPrompt: string            // User-defined instructions (e.g., "Отвечай по-братски, без воды")
  autoGeneratedProfile: string    // LLM-synthesized linguistic profile from session history
  lastAnalyzedSessionHash?: string // Hash to prevent redundant analysis
  updatedAt: string
  enabled: boolean
}

const DEFAULT_PERSONA: LinguisticPersona = {
  tone: 'adaptive',
  customPrompt: '',
  autoGeneratedProfile: '',
  updatedAt: new Date().toISOString(),
  enabled: true
}

export class LinguisticPersonaService {
  private static _filePath: string | null = null
  private static _cache: LinguisticPersona | null = null
  private static _isAnalyzing = false
  private static _debounceTimer: ReturnType<typeof setTimeout> | null = null

  static getFilePath(): string {
    if (!this._filePath) {
      const baseDir = app ? app.getPath('userData') : process.env.APPDATA || process.cwd()
      this._filePath = path.join(baseDir, 'zipply-persona.json')
    }
    return this._filePath
  }

  private static _load(): LinguisticPersona {
    if (this._cache) return this._cache

    try {
      const fp = this.getFilePath()
      let loadPath = fp
      let isLegacy = false

      if (!fs.existsSync(loadPath)) {
        const baseDir = path.dirname(fp)
        const legacyCandidates = [
          path.join(baseDir, 'zipple-persona.json'),
          path.join(baseDir, 'clickcoder-persona.json'),
          path.join(baseDir, 'clickcode-persona.json'),
          path.join(baseDir, 'click-persona.json'),
          path.join(process.cwd(), 'zipple-persona.json'),
          path.join(process.cwd(), 'clickcoder-persona.json'),
          path.join(process.cwd(), 'clickcode-persona.json'),
          path.join(process.cwd(), 'click-persona.json')
        ]
        for (const candidate of legacyCandidates) {
          if (fs.existsSync(candidate)) {
            loadPath = candidate
            isLegacy = true
            break
          }
        }
      }

      if (fs.existsSync(loadPath)) {
        const raw = fs.readFileSync(loadPath, 'utf8')
        const data = JSON.parse(raw)
        if (data && typeof data === 'object') {
          const loaded: LinguisticPersona = {
            ...DEFAULT_PERSONA,
            ...data,
            enabled: data.enabled !== false
          }
          this._cache = loaded
          if (isLegacy) {
            this._save(loaded)
          }
          return loaded
        }
      }
    } catch (e) {
      console.warn('[LinguisticPersonaService] Load error, using defaults:', e)
    }

    const fallback: LinguisticPersona = { ...DEFAULT_PERSONA }
    this._cache = fallback
    return fallback
  }

  private static _save(persona: LinguisticPersona): void {
    this._cache = persona
    try {
      const filePath = this.getFilePath()
      const dir = path.dirname(filePath)
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true })
      }
      fs.writeFileSync(filePath, JSON.stringify(persona, null, 2), 'utf8')
    } catch (e) {
      console.error('[LinguisticPersonaService] Save error:', e)
    }
  }

  static getPersona(): LinguisticPersona {
    return { ...this._load() }
  }

  static updatePersona(patch: Partial<LinguisticPersona>): LinguisticPersona {
    const current = this._load()
    const updated: LinguisticPersona = {
      ...current,
      ...patch,
      updatedAt: new Date().toISOString()
    }
    this._save(updated)
    return { ...updated }
  }

  /**
   * Generates a fast hash of recent session titles & summaries to detect changes.
   */
  private static _calculateSessionsHash(sessions: Array<{ title: string; summary: string }>): string {
    const raw = sessions.map((s) => `${s.title}:${s.summary}`).join('|')
    let hash = 5381
    for (let i = 0; i < raw.length; i++) {
      hash = ((hash << 5) + hash) ^ raw.charCodeAt(i)
      hash = hash >>> 0
    }
    return hash.toString(16)
  }

  /**
   * Schedule debounced profile synthesis after conversations end.
   */
  static scheduleProfileUpdate(config: ChatConfig, delayMs = 6000): void {
    if (this._debounceTimer) clearTimeout(this._debounceTimer)
    this._debounceTimer = setTimeout(() => {
      this.synthesizeProfileAsync(config, false).catch(() => {})
    }, delayMs)
  }

  /**
   * Analyzes recent session summaries and user messages to synthesize
   * a compact, natural linguistic style profile.
   */
  static async synthesizeProfileAsync(config: ChatConfig, force = false): Promise<string> {
    if (this._isAnalyzing) return this._load().autoGeneratedProfile

    const persona = this._load()
    if (!persona.enabled && !force) return persona.autoGeneratedProfile

    const sessions = SessionSummaryService.getAllSessions().slice(0, 8)
    if (sessions.length === 0) return persona.autoGeneratedProfile

    const currentHash = this._calculateSessionsHash(sessions)
    if (!force && persona.lastAnalyzedSessionHash === currentHash && persona.autoGeneratedProfile.trim()) {
      // Nothing changed, skip redundant LLM call
      return persona.autoGeneratedProfile
    }

    this._isAnalyzing = true

    try {
      const sessionContext = sessions
        .map((s, idx) => `${idx + 1}. Тема: "${s.title}"\n   Резюме: ${s.summary}\n   Ключевые слова: ${s.keywords.join(', ')}`)
        .join('\n\n')

      const prompt = `Проанализируй недавние сессии диалогов пользователя и сформулируй СВЕРХКРАТКИЙ (максимум 2-3 предложения) лингвистический профиль пользователя для естественного общения.

Обрати внимание на:
- Как пользователь здоровается и общается (сленг вроде "вассап", "йоу", "ку", дружеский тон, прямолинейный, деловой, мат/неформальный).
- Предпочитаемая степень краткости (сразу код и суть, или подробные объяснения).
- Характерные словечки или термины.

Правила:
- Текст должен быть в форме четких указаний для ИИ (например: "Пользователь общается легко и по-свойски ('вассап', 'го'). Отвечай живо, без официоза, по делу, с легким юмором при уместности, сразу давай решение.").
- Максимум 30-50 слов. Никакой лишней воды. Без вводных фраз ("Вот профиль:").

Контекст сессий:
${sessionContext}`

      const modelToUse = (config.fastModel && config.fastModel.trim()) || config.model || 'gpt-4o'
      const response = await ChatService.chat(
        {
          ...config,
          model: modelToUse,
          maxTokens: 180,
          temperature: 0.2,
          stream: false
        },
        [
          { role: 'system', content: 'Ты эксперт по стилистике и естественной человеческой речи.' },
          { role: 'user', content: prompt }
        ]
      )

      const profile = response.content?.trim().replace(/^["']|["']$/g, '') || ''
      if (profile && profile.length > 10) {
        persona.autoGeneratedProfile = profile
        persona.lastAnalyzedSessionHash = currentHash
        persona.updatedAt = new Date().toISOString()
        this._save(persona)
        console.log('[LinguisticPersonaService] Synthesized new linguistic profile:', profile)
      }

      return persona.autoGeneratedProfile
    } catch (err) {
      console.warn('[LinguisticPersonaService] Synthesis failed:', err)
      return persona.autoGeneratedProfile
    } finally {
      this._isAnalyzing = false
    }
  }

  /**
   * Builds the compact, zero-bloat system prompt section for human-like communication.
   */
  static getSystemPromptSection(): string {
    const persona = this._load()
    if (!persona.enabled) return ''

    let toneDirective = ''
    switch (persona.tone) {
      case 'casual':
        toneDirective = 'Общайся свободно, по-дружески, как опытный напарник. Легкий живой тон.'
        break
      case 'direct':
        toneDirective = 'Будь предельно краток, точен и прямолинеен. Минимум рассуждений, максимум чистого решения.'
        break
      case 'friendly':
        toneDirective = 'Доброжелательный, поддерживающий тон, понятные пояснения и готовность помочь.'
        break
      case 'mentor':
        toneDirective = 'Тон мудрого старшего специалиста/ментора: структурированно, давай полезные инсайты и лучшие практики.'
        break
      case 'adaptive':
      default:
        toneDirective = 'Адаптируйся под тон пользователя: если он пишет просторечно/на сленге ("вассап", "ку", "йоу") — отвечай так же естественно и по-свойски; если он краток и строг — отвечай лаконично и технично.'
        break
    }

    const parts: string[] = []

    parts.push(`## Natural Human Communication Directive`)
    parts.push(`- **Живая речь**: Разговаривай как живой человек и надежный напарник. Категорически избегай шаблонной роботизированности ("Конечно! Я с радостью помогу вам с...", "Безусловно, давайте разберем...", "Как искусственный интеллект...").`)
    parts.push(`- **Тональность**: ${toneDirective}`)
    parts.push(`- **Никакой воды**: Сразу переходи к сути задачи. Не повторяй условия вопроса в первом предложении.`)

    if (persona.autoGeneratedProfile && persona.autoGeneratedProfile.trim()) {
      parts.push(`- **Стиль пользователя**: ${persona.autoGeneratedProfile.trim()}`)
    }

    if (persona.customPrompt && persona.customPrompt.trim()) {
      parts.push(`- **Личные пожелания к речи**: ${persona.customPrompt.trim()}`)
    }

    return '\n' + parts.join('\n') + '\n'
  }
}
