/// <reference types="vite/client" />

import type { AgentEvent } from '../../shared/agentEvents'

export interface MemoryItemUI {
  id: string
  category: 'user_preference' | 'project_fact' | 'procedural_workflow' | 'fact'
  content: string
  tags: string[]
  importance: number
  createdAt: string
  updatedAt: string
  embedding?: number[]
  hitCount?: number
  similarityScore?: number
}

export interface SessionSummaryUI {
  id: string
  chatId: string
  title: string
  summary: string
  keywords: string[]
  createdAt: string
  messageCount: number
}

export interface LinguisticPersonaUI {
  tone: 'adaptive' | 'casual' | 'direct' | 'friendly' | 'mentor'
  customPrompt: string
  autoGeneratedProfile: string
  updatedAt: string
  enabled: boolean
}

export type SkillSourceType = 'global' | 'workspace' | 'codex'

export interface SkillItemUI {
  id: string
  name: string
  description: string
  content: string
  isCore: boolean
  source: SkillSourceType
  tags: string[]
  globs?: string[]
  triggers?: string[]
  tools?: string[]
  createdAt: string
  updatedAt: string
  filePath: string
  isFolder?: boolean
  files?: string[]
  enabled?: boolean
  suite?: string
  embedding?: number[]
  similarityScore?: number
  matchReason?: string
  matchedTriggers?: string[]
}

export interface WindowApi {
  window: {
    minimize: () => Promise<void>
    maximize: () => Promise<boolean>
    close: () => Promise<void>
    isMaximized: () => Promise<boolean>
  }
  agent: {
    chat: (history: any[], settings: any, requestId: string, agentId?: string) => void
    cancel: (requestId: string) => void
    generateTitle: (userMessage: string, settings: any) => Promise<string>
    generateRoundSummary: (steps: any[], userMessage: string, settings: any) => Promise<string | null>
    onEvent: (callback: (event: AgentEvent) => void) => () => void
    removeListeners: () => void
  }
  memory: {
    getAll: () => Promise<MemoryItemUI[]>
    add: (memoryData: any) => Promise<{ item: MemoryItemUI | null; duplicate: MemoryItemUI | null }>
    update: (id: string, patch: any) => Promise<MemoryItemUI | null>
    delete: (id: string) => Promise<boolean>
    search: (query?: string, category?: string | null, settings?: any) => Promise<MemoryItemUI[]>
    clear: () => Promise<boolean>
    getCoreSummary: () => Promise<string>
    updateCoreSummary: (summary: string) => Promise<boolean>
    generateCoreSummary: (settings?: any, force?: boolean) => Promise<string>
  }
  persona: {
    get: () => Promise<LinguisticPersonaUI>
    update: (patch: Partial<LinguisticPersonaUI>) => Promise<LinguisticPersonaUI>
    generate: (settings?: any, force?: boolean) => Promise<string>
  }
  session: {
    getAll: () => Promise<SessionSummaryUI[]>
    getRelevant: (query: string, limit?: number) => Promise<SessionSummaryUI[]>
    delete: (id: string) => Promise<boolean>
    clear: () => Promise<void>
  }
  skills: {
    getAll: (workspacePath?: string) => Promise<SkillItemUI[]>
    search: (query: string, filterType?: string, workspacePath?: string, settings?: any) => Promise<SkillItemUI[]>
    save: (data: {
      name: string
      description: string
      content: string
      isCore?: boolean
      metadata?: { globs?: string[]; triggers?: string[]; tags?: string[]; tools?: string[] }
    }) => Promise<{ success: boolean; skill?: SkillItemUI; error?: string }>
    delete: (name: string, isCore?: boolean, sourcePath?: string) =>
      Promise<{ success: boolean; error?: string }>
    toggleType: (name: string, sourcePath?: string) =>
      Promise<{ success: boolean; newIsCore?: boolean; error?: string }>
    read: (name: string, resourcePath?: string, workspacePath?: string) =>
      Promise<{ success: boolean; content?: string; resourceContent?: string; files?: string[]; metadata?: any; error?: string }>
    importFromPath: (filePath: string, isCore?: boolean) =>
      Promise<{ success: boolean; skill?: SkillItemUI; count?: number; error?: string }>
    importFromUrl: (url: string, isCore?: boolean) =>
      Promise<{ success: boolean; skill?: SkillItemUI; error?: string }>
    toggleEnabled: (name: string, enabled?: boolean) =>
      Promise<{ success: boolean; enabled: boolean }>
    togglePackage: (skillNames: string[], enabled: boolean) =>
      Promise<{ success: boolean; count: number }>
    deleteMultiple: (items: Array<{ name: string; isCore?: boolean; sourcePath?: string }>) =>
      Promise<{ success: boolean; deletedCount: number }>
    openFolder: () => Promise<{ success: boolean; path: string; error?: string }>
    syncExternal: () => Promise<{ success: boolean; importedCount: number; skills: SkillItemUI[]; error?: string }>
    selectSkillFileOrDir: () => Promise<string | null>
  }
  mcp?: {
    getAllServers: () => Promise<import('./types/mcp').McpServerItemUI[]>
    saveServer: (server: Partial<import('./types/mcp').McpServerConfig> & { name: string }) =>
      Promise<{ success: boolean; server?: import('./types/mcp').McpServerItemUI; error?: string }>
    deleteServer: (id: string) =>
      Promise<{ success: boolean; error?: string }>
    toggleServer: (id: string, enabled?: boolean) =>
      Promise<{ success: boolean; server?: import('./types/mcp').McpServerItemUI; error?: string }>
    testConnection: (id: string) =>
      Promise<{ success: boolean; server?: import('./types/mcp').McpServerItemUI; error?: string; latencyMs?: number }>
    getTools: (serverId?: string) =>
      Promise<import('./types/mcp').McpDiscoveredTool[]>
    importConfig: (jsonContent: string) =>
      Promise<{ success: boolean; count: number; error?: string }>
    exportConfig: () =>
      Promise<{ success: boolean; json?: string; error?: string }>
  }
  dialog: {
    selectDirectory: (defaultPath?: string) => Promise<string | null>
  }
  projects: {
    list: (baseDir?: string) => Promise<{ name: string; path: string }[]>
    create: (baseDir: string, name: string) => Promise<{ name: string; path: string } | null>
  }
  models?: {
    fetchRemote: (data: { baseUrl: string; apiKey?: string; providerId?: string }) => Promise<string[]>
    testConnection: (data: { baseUrl: string; apiKey?: string; model?: string; providerId?: string }) =>
      Promise<{ status: 'success' | 'error'; message: string; latencyMs?: number }>
    scanLocal: () => Promise<Array<{
      providerId: 'ollama' | 'lmstudio' | 'vllm'
      name: string
      port: number
      baseUrl: string
      models: string[]
      status: 'online'
      latencyMs?: number
    }>>
  }
  storage?: {
    getInfo: () => Promise<{
      platform: 'win32' | 'darwin' | 'linux' | string
      homeDir: string
      userDataDir: string
      storageDir: string
      defaultProjectsDir: string
    }>
    getMetrics: () => Promise<{
      chatsCount: number
      projectsCount: number
      hasAiConfig: boolean
      hasAppearance: boolean
      storageSizeBytes: number
      lastUpdated: string
    }>
    getStore: <T = any>(storeName: string, defaultValue?: T) => Promise<T>
    setStore: <T = any>(storeName: string, data: T, debounceMs?: number) => Promise<boolean>
    getItem: <T = any>(key: string, defaultValue?: T) => Promise<T>
    setItem: (key: string, value: any) => Promise<boolean>
    removeItem: (key: string) => Promise<boolean>
    openFolder: () => Promise<{ success: boolean; path: string; error?: string }>
    exportBackup: () => Promise<{ success: boolean; filePath?: string; cancelled?: boolean; error?: string }>
    importBackup: () => Promise<{ success: boolean; details?: string; cancelled?: boolean; error?: string }>
  }
  files: {
    readDir: (dirPath: string) => Promise<{
      success: boolean
      items?: Array<{
        name: string
        path: string
        isDirectory: boolean
        isFile: boolean
        size: number
        mtime: number
        ext: string
      }>
      error?: string
    }>
    createFile: (filePath: string) => Promise<{ success: boolean; error?: string }>
    createDir: (dirPath: string) => Promise<{ success: boolean; error?: string }>
    rename: (oldPath: string, newPath: string) => Promise<{ success: boolean; error?: string }>
    move: (sourcePath: string, targetDirPath: string) => Promise<{ success: boolean; destPath?: string; error?: string }>
    delete: (targetPath: string) => Promise<{ success: boolean; error?: string }>
    reveal: (targetPath: string) => Promise<boolean>
  }
  terminal: {
    run: (params: { runId: string; command: string; cwd?: string; sessionId?: string }) => void
    sendInput: (params: { targetId: string; input: string }) => Promise<{ success: boolean; message: string }>
    syncSessions: (sessions: any[], activeSessionId?: string) => void
    kill: (runId?: string) => Promise<boolean>
    getDefaultCwd: () => Promise<string>
    onData: (callback: (data: { runId: string; text: string; stream: 'stdout' | 'stderr' }) => void) => () => void
    onExit: (callback: (data: { runId: string; code: number }) => void) => () => void
    onAiStart: (callback: (data: { runId: string; command: string; cwd: string; isBackground?: boolean }) => void) => () => void
    onAiData: (callback: (data: { runId: string; text: string }) => void) => () => void
    onAiExit: (callback: (data: { runId: string; code?: number | null }) => void) => () => void
  }
  setZoomFactor: (factor: number) => void
}

declare global {
  interface Window {
    api: WindowApi
  }
}

