const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')
const os = require('os')

const rootDir = path.resolve(__dirname, '..')
const pkg = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8'))
const distDir = path.join(rootDir, 'dist')
const linuxUnpacked = path.join(distDir, 'linux-unpacked')
const buildDir = path.join(rootDir, 'build')
const iconsDir = path.join(buildDir, 'icons')

const pkgName = 'zipply'
const pkgVersion = pkg.version
const pkgRel = '1'
const arch = 'x86_64'

// 1. Ensure linux-unpacked exists
if (!fs.existsSync(linuxUnpacked)) {
  console.log('===> 1. Packaging Linux directory with electron-builder...')
  execSync('npx electron-builder --linux dir', { cwd: rootDir, stdio: 'inherit' })
} else {
  console.log('===> 1. Reusing existing linux-unpacked directory...')
}

const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'zipply-arch-'))

try {
  const stageDir = path.join(tmpDir, 'stage')
  const optAppDir = path.join(stageDir, 'opt', 'zipply')
  const usrBinDir = path.join(stageDir, 'usr', 'bin')
  const usrAppsDir = path.join(stageDir, 'usr', 'share', 'applications')
  const usrPixmapsDir = path.join(stageDir, 'usr', 'share', 'pixmaps')

  fs.mkdirSync(optAppDir, { recursive: true })
  fs.mkdirSync(usrBinDir, { recursive: true })
  fs.mkdirSync(usrAppsDir, { recursive: true })
  fs.mkdirSync(usrPixmapsDir, { recursive: true })

  console.log('===> 2. Copying application files...')
  function copyRecursive(src, dst) {
    const stat = fs.statSync(src)
    if (stat.isDirectory()) {
      if (!fs.existsSync(dst)) fs.mkdirSync(dst, { recursive: true })
      for (const file of fs.readdirSync(src)) {
        copyRecursive(path.join(src, file), path.join(dst, file))
      }
    } else {
      fs.copyFileSync(src, dst)
    }
  }
  copyRecursive(linuxUnpacked, optAppDir)

  // Copy icons to hicolor
  const iconSizes = [16, 24, 32, 48, 64, 128, 256, 512]
  for (const s of iconSizes) {
    const sizeDir = path.join(stageDir, 'usr', 'share', 'icons', 'hicolor', `${s}x${s}`, 'apps')
    fs.mkdirSync(sizeDir, { recursive: true })
    const iconSrc = path.join(iconsDir, `${s}x${s}.png`)
    if (fs.existsSync(iconSrc)) {
      fs.copyFileSync(iconSrc, path.join(sizeDir, `${pkgName}.png`))
    }
  }
  if (fs.existsSync(path.join(iconsDir, '512x512.png'))) {
    fs.copyFileSync(path.join(iconsDir, '512x512.png'), path.join(usrPixmapsDir, `${pkgName}.png`))
  }

  // Create .desktop file
  const desktopContent = `[Desktop Entry]
Name=Zipply
Comment=${pkg.description || 'Zipply - Simple Ai Agent'}
Exec=/opt/zipply/zipply %U
Terminal=false
Type=Application
Icon=zipply
StartupWMClass=zipply
Categories=Development;IDE;
`
  fs.writeFileSync(path.join(usrAppsDir, `${pkgName}.desktop`), desktopContent.replace(/\r\n/g, '\n'), 'utf8')

  // Create symlink / wrapper in /usr/bin
  const binWrapper = `#!/bin/sh
exec /opt/zipply/zipply "$@"
`
  fs.writeFileSync(path.join(usrBinDir, pkgName), binWrapper.replace(/\r\n/g, '\n'), { encoding: 'utf8', mode: 0o755 })

  // Calculate installed size in bytes
  function getInstalledSize(dir) {
    let size = 0
    for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, item.name)
      if (item.isDirectory()) {
        size += getInstalledSize(p)
      } else {
        size += fs.statSync(p).size
      }
    }
    return size
  }
  const installedSize = getInstalledSize(stageDir)

  console.log('===> 3. Generating Arch Linux metadata (.PKGINFO & .INSTALL)...')
  const buildDate = Math.floor(Date.now() / 1000)
  const pkgInfoContent = `# Generated by Zipply Packaging
pkgname = ${pkgName}
pkgbase = ${pkgName}
pkgver = ${pkgVersion}-${pkgRel}
pkgdesc = ${pkg.description || 'Zipply - Simple Ai Agent'}
url = https://github.com/AmnesiaCode888/Zipply
builddate = ${buildDate}
packager = ${pkg.author || 'Zipply Team <amnesiacoder@gmail.com>'}
size = ${installedSize}
arch = ${arch}
license = BSL-1.1
depend = gtk3
depend = libnotify
depend = nss
depend = libxss
depend = libxtst
depend = libsecret
depend = alsa-lib
depend = libappindicator-gtk3
depend = xdg-utils
optdepend = c-ares: Async DNS resolver
optdepend = ffmpeg: Multimedia playback
install = .INSTALL
`
  fs.writeFileSync(path.join(stageDir, '.PKGINFO'), pkgInfoContent.replace(/\r\n/g, '\n'), 'utf8')

  const installScriptlet = `post_install() {
    command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database -q || true
    command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
    chmod 4755 /opt/zipply/chrome-sandbox 2>/dev/null || true
    chmod 755 /opt/zipply/zipply 2>/dev/null || true
    chmod 755 /usr/bin/zipply 2>/dev/null || true
}

post_upgrade() {
    post_install
}

post_remove() {
    command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database -q || true
    command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || true
}
`
  fs.writeFileSync(path.join(stageDir, '.INSTALL'), installScriptlet.replace(/\r\n/g, '\n'), 'utf8')

  console.log(`===> 4. Packing Arch Linux package (${pkgName}-${pkgVersion}-${pkgRel}-${arch}.pkg.tar.zst)...`)
  const pacmanFileName = `${pkgName}-${pkgVersion}-${pkgRel}-${arch}.pkg.tar.zst`
  const pacmanFilePath = path.join(distDir, pacmanFileName)

  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true })
  }

  const tempOutputFile = path.join(tmpDir, 'output.pkg.tar.zst')

  // In pacman packages, .PKGINFO and .INSTALL should be at the root of the archive along with opt and usr
  const entries = ['.PKGINFO', '.INSTALL', 'opt', 'usr']
  const itemsArg = entries.map((e) => `"${e}"`).join(' ')

  execSync(`tar --zstd -cf "${tempOutputFile}" ${itemsArg}`, {
    cwd: stageDir,
    stdio: 'inherit'
  })

  fs.copyFileSync(tempOutputFile, pacmanFilePath)

  // Generate AUR PKGBUILD in dist directory
  const pkgbuildContent = `# Maintainer: ${pkg.author || 'Zipply Team <amnesiacoder@gmail.com>'}
pkgname=zipply-bin
pkgver=${pkgVersion}
pkgrel=${pkgRel}
pkgdesc="${pkg.description || 'Zipply - Simple Ai Agent'}"
arch=('x86_64')
url="https://github.com/AmnesiaCode888/Zipply"
license=('custom:BSL-1.1')
depends=('gtk3' 'libnotify' 'nss' 'libxss' 'libxtst' 'libsecret' 'alsa-lib' 'libappindicator-gtk3' 'xdg-utils')
optdepends=('c-ares: Async DNS resolver' 'ffmpeg: Multimedia playback')
provides=('zipply')
conflicts=('zipply')
source=("https://github.com/AmnesiaCode888/Zipply/releases/download/v\${pkgver}-beta/${pacmanFileName}")
sha256sums=('SKIP')

package() {
    cp -dr --no-preserve=ownership "\${srcdir}"/{opt,usr} "\${pkgdir}/"
}
`
  fs.writeFileSync(path.join(distDir, 'PKGBUILD'), pkgbuildContent.replace(/\r\n/g, '\n'), 'utf8')

  const sizeMb = (fs.statSync(pacmanFilePath).size / (1024 * 1024)).toFixed(2)
  console.log(`\n========================================`)
  console.log(`Successfully created Arch Linux package!`)
  console.log(`Package: ${pacmanFilePath}`)
  console.log(`PKGBUILD: ${path.join(distDir, 'PKGBUILD')}`)
  console.log(`Size: ${sizeMb} MB`)
  console.log(`Installed size: ${(installedSize / (1024 * 1024)).toFixed(2)} MB`)
  console.log(`========================================\n`)

  fs.rmSync(tmpDir, { recursive: true, force: true })
} catch (err) {
  fs.rmSync(tmpDir, { recursive: true, force: true })
  console.error('Fatal Arch build error:', err)
  process.exit(1)
}
