import assert from 'assert'
import { toolRegistry } from '../src/main/agent/tools/ToolRegistry'
import { agentRegistry } from '../src/main/agent/index'
import { ToolExecutor } from '../src/main/agent/core/ToolExecutor'
import { BrowserTool } from '../src/main/agent/tools/BrowserTool'

async function runBrowserIntegrationTests(): Promise<void> {
  console.log('🧪 Starting Browser Tool & Integration Verification Suite...\n')

  // Test 1: Tool registration
  console.log('▶ Test 1: Verify BrowserTool is registered in toolRegistry...')
  const browserTool = toolRegistry.getTool('browser')
  assert(browserTool, 'BrowserTool should be present in toolRegistry')
  assert(browserTool instanceof BrowserTool, 'Tool should be an instance of BrowserTool')
  assert.strictEqual(browserTool.name, 'browser')
  console.log('  ✅ BrowserTool successfully retrieved from toolRegistry.')

  // Test 2: Agent tool availability
  console.log('▶ Test 2: Verify browser tool is wired into agents...')
  const zipplyAgent = agentRegistry.getAgent('zipply')
  const workerAgent = agentRegistry.getAgent('worker')
  const architectAgent = agentRegistry.getAgent('architect')

  assert(
    zipplyAgent.getTools().some((t) => t.name === 'browser'),
    'zipplyAgent should have browser tool'
  )
  assert(
    workerAgent.getTools().some((t) => t.name === 'browser'),
    'workerAgent should have browser tool'
  )
  assert(
    architectAgent.getTools().some((t) => t.name === 'browser'),
    'architectAgent should have browser tool'
  )
  console.log('  ✅ browser tool successfully wired into zipplyAgent, workerAgent, and architectAgent.')

  // Test 3: OpenAI Schema Generation for Gemini / OpenAI
  console.log('▶ Test 3: Verify ToolExecutor generates valid function calling schema for browser...')
  const definitions = ToolExecutor.buildToolDefs(zipplyAgent)
  const browserDef = definitions.find((d) => d.function.name === 'browser')
  assert(browserDef, 'browser tool definition should be generated by ToolExecutor')
  assert(browserDef.function.parameters, 'parameters should exist')
  const props = (browserDef.function.parameters as any).properties
  assert(props.action, 'action property should exist')
  assert(Array.isArray(props.action.enum), 'action enum should be an array')
  assert(props.action.enum.includes('navigate'), 'action enum should include navigate')
  assert(props.action.enum.includes('screenshot'), 'action enum should include screenshot')
  assert(props.action.enum.includes('click'), 'action enum should include click')
  assert(props.action.enum.includes('type'), 'action enum should include type')
  assert(props.action.enum.includes('get_content'), 'action enum should include get_content')
  assert(props.url, 'url property should exist')
  assert(props.selector, 'selector property should exist')
  assert(props.text, 'text property should exist')
  console.log('  ✅ Function calling schema for browser verified cleanly.')

  // Test 4: Validation checks
  console.log('▶ Test 4: Verify BrowserTool parameter validation...')
  const missingUrlErr = browserTool.validate(JSON.stringify({ action: 'navigate' }))
  assert(missingUrlErr && missingUrlErr.includes('url'), 'Should reject navigate without url')

  const missingTypeErr = browserTool.validate(JSON.stringify({ action: 'type' }))
  assert(missingTypeErr && missingTypeErr.includes('text'), 'Should reject type without text')

  const missingClickErr = browserTool.validate(JSON.stringify({ action: 'click' }))
  assert(missingClickErr && (missingClickErr.includes('selector') || missingClickErr.includes('text')), 'Should reject click without selector or text')

  const validNavigate = browserTool.validate(JSON.stringify({ action: 'navigate', url: 'https://example.com' }))
  assert.strictEqual(validNavigate, null, 'Valid navigate should pass validation')

  const validClick = browserTool.validate(JSON.stringify({ action: 'click', selector: 'button.btn' }))
  assert.strictEqual(validClick, null, 'Valid click should pass validation')
  console.log('  ✅ Parameter validation rules verified.')

  console.log('\n🎉 ALL BROWSER INTEGRATION VERIFICATION TESTS PASSED CLEANLY!')
}

runBrowserIntegrationTests().catch((err) => {
  console.error('❌ Verification failed:', err)
  process.exit(1)
})
